server:
    compression:
      enabled: true
      min-response-size: 0
    tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 192\\.168\\.\\d{1,3}\\.\\d{1,3}
    use-forward-headers: true

      #port: 80
    address: 127.0.0.1

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/smarthome?characterEncoding=utf8
        username: root
        password: se1124
        tomcat:
          max-active: 10
          max-idle: 8
          max-wait: 10000
          min-evictable-idle-time-millis: 1000
          min-idle: 8
          time-between-eviction-runs-millis: 1
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
